theme = "nordic"

[editor]
end-of-line-diagnostics = "hint"
line-number = "relative"
mouse = false
bufferline = "always"
rulers = [100]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"

[editor.file-picker]
hidden = false

[keys.normal]
"space" = { "A" = {"p" = ":pipe /home/rob/.config/helix/scripts/helix_relative_path.py"}}
"A-pagedown" = ":buffer-next"
"A-pageup" = ":buffer-previous"
