theme = "nordic"

[editor]
end-of-line-diagnostics = "hint"
line-number = "relative"
mouse = false
bufferline = "always"
rulers = [100]
cursorline = true
popup-border = "all"
auto-pairs = false
jump-label-alphabet = "dfghjkieruwonvls"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "diagnostics", "spinner", "read-only-indicator", "file-modification-indicator", "version-control"]
right = ["selections", "register", "position", "file-encoding"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
separator = "|"

[keys.normal]
"A-pagedown" = ":buffer-next"
"A-pageup" = ":buffer-previous"
"A-w" = ":buffer-close"

[keys.normal.space.space]
"a" = { "p" = ":pipe python /home/rob/.config/helix/scripts/helix_relative_path.py" }

[keys.normal.space.space.b.q.n]
"a" = ":pipe python /home/rob/.config/helix/scripts/helix_build_query_call.py --db 'n'"
"o" = ":pipe python /home/rob/.config/helix/scripts/helix_build_query_call.py --db 'n' --as-polars"
[keys.normal.space.space.b.q.m]
"a" = ":pipe python /home/rob/.config/helix/scripts/helix_build_query_call.py --db 'm'"
"o" = ":pipe python /home/rob/.config/helix/scripts/helix_build_query_call.py --db 'm' --as-polars"
